name: Simple Test Runner

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  test-job:
    runs-on: [self-hosted, macOS, ARM64, global]  # Ensure all labels match
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a simple command
        run: echo "The self-hosted runner is working!"
