jobs:
  test-job:
    runs-on: [self-hosted, macOS, X64, global]  # Ensure all labels match
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a simple command
        run: echo "The self-hosted runner is working!"
